name: Jest Test

on:
  # Run tests for any PRs.
  pull_request:

env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: Install package
        run: yarn
      - name: Run Test
        run: yarn jest
