name: Jest Test

on:
  # Run tests for any PRs.
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install package
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Run Test
        run: yarn jest
