name: Code Lint

on:
  # Run tests for any PRs.
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Show commid ID
        run: git show -s --format=%H
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-v16-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Install package
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Run Test
        run: yarn lintCheckOnly
