name: Publish-Execute
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build:
    name: publish-execute
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'publish'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install package
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
