name: Publish-Execute
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build:
    name: publish-execute
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'publish'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@aspulse'
      - name: Install package
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        run: yarn build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
