
name: Publish-GitHub-NPM
on:
  push:
    branches: [main]
    tags-ignore: *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@aspulse'
      - name: Install package
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Version Up
        run: npm version patch > version.txt
      - name: Setup git configuration
        run: |
          git config user.name Version-Updater
          git config user.email github-actions@github.com
      - name: Commit new Version
        run: |
          git add package.json
          git commit -m "VersionUp to ${cat version.txt}"
          git tag ${cat version.txt}
          git push --tags
