
name: Publish-GitHubNpm-Patch
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git configuration
        run: |
          git config user.name Version-Updater
          git config user.email github-actions@github.com
      - name: Pull
        run: git pull origin main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@aspulse'
      - name: Create Branch
        run: |
          git checkout -b publish
          git push --set-upstream origin publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Version Up
        run: |
          NEWVER=$(npm version patch --no-git-tag-version)
          echo "newver=$NEWVER" >> $GITHUB_ENV
          git push
      - name: Create Publish PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: publish
          base: main
          commit-message: VersionUp to ${{env.newver}}
          committer: Version-Updater <github-actions@github.com>
          body: |
            @AsPulse
            Publish GitHub NPM Registry ${{env.newver}}
          title: "Publish ${{env.newver}}"
          draft: false
          reviewers: AsPulse
          assignees: AsPulse
          delete-branch: true
          token: ${{ secrets.REPO_PAT }}
